#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    Dec 15, 2018 09:41:53 PM CAT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import AdminLogin_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = AdminLogin (root)
    AdminLogin_support.init(root, top)
    root.mainloop()

w = None
def create_AdminLogin(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = AdminLogin (w)
    AdminLogin_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_AdminLogin():
    global w
    w.destroy()
    w = None

class AdminLogin:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 
        font9 = "-family {Segoe UI} -size 12 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"

        top.geometry("351x220+293+155")
        top.title("Admin Login")
        top.configure(background="#c6b0c0")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Email = tk.Entry(top)
        self.Email.place(relx=0.299, rely=0.273,height=30, relwidth=0.667)
        self.Email.configure(background="white")
        self.Email.configure(disabledforeground="#a3a3a3")
        self.Email.configure(font="TkFixedFont")
        self.Email.configure(foreground="#000000")
        self.Email.configure(highlightbackground="#d9d9d9")
        self.Email.configure(highlightcolor="black")
        self.Email.configure(insertbackground="black")
        self.Email.configure(selectbackground="#c4c4c4")
        self.Email.configure(selectforeground="black")

        self.Password = tk.Entry(top)
        self.Password.place(relx=0.299, rely=0.591,height=30, relwidth=0.667)
        self.Password.configure(background="white")
        self.Password.configure(disabledforeground="#a3a3a3")
        self.Password.configure(font="TkFixedFont")
        self.Password.configure(foreground="#000000")
        self.Password.configure(highlightbackground="#d9d9d9")
        self.Password.configure(highlightcolor="black")
        self.Password.configure(insertbackground="black")
        self.Password.configure(selectbackground="#c4c4c4")
        self.Password.configure(selectforeground="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.085, rely=0.273, height=21, width=34)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#c6b0c0")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Email''')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.085, rely=0.591, height=21, width=54)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#c6b0c0")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Password''')

        self.Login = tk.Button(top)
        self.Login.place(relx=0.798, rely=0.818, height=34, width=57)
        self.Login.configure(activebackground="#ececec")
        self.Login.configure(activeforeground="#000000")
        self.Login.configure(background="#79517c")
        self.Login.configure(command=self.AdminLogin)
        self.Login.configure(disabledforeground="#a3a3a3")
        self.Login.configure(foreground="#000000")
        self.Login.configure(highlightbackground="#d9d9d9")
        self.Login.configure(highlightcolor="black")
        self.Login.configure(pady="0")
        self.Login.configure(text='''Login''')

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.0, rely=0.0, height=41, width=354)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#b596b1")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font=font9)
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Login As Admin''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

    def AdminLogin(self):
        AdminLogin_support.AdminLogin(self.Email.get(),self.Password.get())
if __name__ == '__main__':
    vp_start_gui()





