#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    Dec 15, 2018 10:20:03 PM CAT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import StudentHome_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Student (root)
    StudentHome_support.init(root, top)
    top.FillBorrowed()
    root.mainloop()

w = None
def create_Student(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Student (w)
    StudentHome_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Student():
    global w
    w.destroy()
    w = None

class Student:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("624x467+323+133")
        top.title("Student Home")
        top.configure(background="#d9d9d9")

        self.style.configure('TNotebook.Tab', background=_bgcolor)
        self.style.configure('TNotebook.Tab', foreground=_fgcolor)
        self.style.map('TNotebook.Tab', background=
            [('selected', _compcolor), ('active',_ana2color)])
        self.TNotebook2 = ttk.Notebook(top)
        self.TNotebook2.place(relx=0.0, rely=0.0, relheight=1.0, relwidth=1.0)
        self.TNotebook2.configure(width=624)
        self.TNotebook2.configure(takefocus="")
        self.TNotebook2_t0 = tk.Frame(self.TNotebook2)
        self.TNotebook2.add(self.TNotebook2_t0, padding=3)
        self.TNotebook2.tab(0, text="Borrowed Books", compound="left"
                ,underline="-1", )
        self.TNotebook2_t0.configure(background="#d9d9d9")
        self.TNotebook2_t0.configure(highlightbackground="#d9d9d9")
        self.TNotebook2_t0.configure(highlightcolor="black")
        self.TNotebook2_t1 = tk.Frame(self.TNotebook2)
        self.TNotebook2.add(self.TNotebook2_t1, padding=3)
        self.TNotebook2.tab(1, text="Books",compound="left",underline="-1",)
        self.TNotebook2_t1.configure(background="#d9d9d9")
        self.TNotebook2_t1.configure(highlightbackground="#d9d9d9")
        self.TNotebook2_t1.configure(highlightcolor="black")
        self.TNotebook2_t2 = tk.Frame(self.TNotebook2)
        self.TNotebook2.add(self.TNotebook2_t2, padding=3)
        self.TNotebook2.tab(2, text="Publishers", compound="none", underline="-1"
                ,)
        self.TNotebook2_t2.configure(background="#d9d9d9")
        self.TNotebook2_t2.configure(highlightbackground="#d9d9d9")
        self.TNotebook2_t2.configure(highlightcolor="black")

        self.style.configure('Treeview.Heading',  font="TkDefaultFont")
        self.Scrolledtreeview2 = ScrolledTreeView(self.TNotebook2_t0)
        self.Scrolledtreeview2.place(relx=0.0, rely=0.0, relheight=0.855
                , relwidth=0.994)
        self.Scrolledtreeview2.configure(columns="Col1 Col2 Col3")
        self.Scrolledtreeview2.heading("#0",text="Borrow ID")
        self.Scrolledtreeview2.heading("#0",anchor="center")
        self.Scrolledtreeview2.column("#0",width="200")
        self.Scrolledtreeview2.column("#0",minwidth="20")
        self.Scrolledtreeview2.column("#0",stretch="1")
        self.Scrolledtreeview2.column("#0",anchor="w")
        self.Scrolledtreeview2.heading("Col1",text="Book Name")
        self.Scrolledtreeview2.heading("Col1",anchor="center")
        self.Scrolledtreeview2.column("Col1",width="201")
        self.Scrolledtreeview2.column("Col1",minwidth="20")
        self.Scrolledtreeview2.column("Col1",stretch="1")
        self.Scrolledtreeview2.column("Col1",anchor="w")
        self.Scrolledtreeview2.heading("Col2",text="Borrow Date")
        self.Scrolledtreeview2.heading("Col2",anchor="center")
        self.Scrolledtreeview2.column("Col2",width="99")
        self.Scrolledtreeview2.column("Col2",minwidth="20")
        self.Scrolledtreeview2.column("Col2",stretch="1")
        self.Scrolledtreeview2.column("Col2",anchor="w")
        self.Scrolledtreeview2.heading("Col3",text="End Borrow Date")
        self.Scrolledtreeview2.heading("Col3",anchor="center")
        self.Scrolledtreeview2.column("Col3",width="97")
        self.Scrolledtreeview2.column("Col3",minwidth="20")
        self.Scrolledtreeview2.column("Col3",stretch="1")
        self.Scrolledtreeview2.column("Col3",anchor="w")

        self.Button2 = tk.Button(self.TNotebook2_t0)
        self.Button2.place(relx=0.016, rely=0.884, height=34, width=597)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Borrow New Book''')
        self.Button2.configure(width=597)

        self.Scrolledtreeview3 = ScrolledTreeView(self.TNotebook2_t1)
        self.Scrolledtreeview3.place(relx=0.0, rely=0.0, relheight=0.855
                , relwidth=1.006)
        self.Scrolledtreeview3.configure(columns="Col1 Col2")
        self.Scrolledtreeview3.heading("#0",text="Book ID")
        self.Scrolledtreeview3.heading("#0",anchor="center")
        self.Scrolledtreeview3.column("#0",width="201")
        self.Scrolledtreeview3.column("#0",minwidth="20")
        self.Scrolledtreeview3.column("#0",stretch="1")
        self.Scrolledtreeview3.column("#0",anchor="w")
        self.Scrolledtreeview3.heading("Col1",text="Book Name")
        self.Scrolledtreeview3.heading("Col1",anchor="center")
        self.Scrolledtreeview3.column("Col1",width="207")
        self.Scrolledtreeview3.column("Col1",minwidth="20")
        self.Scrolledtreeview3.column("Col1",stretch="1")
        self.Scrolledtreeview3.column("Col1",anchor="w")
        self.Scrolledtreeview3.heading("Col2",text="Book Publisher")
        self.Scrolledtreeview3.heading("Col2",anchor="center")
        self.Scrolledtreeview3.column("Col2",width="197")
        self.Scrolledtreeview3.column("Col2",minwidth="20")
        self.Scrolledtreeview3.column("Col2",stretch="1")
        self.Scrolledtreeview3.column("Col2",anchor="w")

        self.Button3 = tk.Button(self.TNotebook2_t1)
        self.Button3.place(relx=0.355, rely=0.884, height=34, width=77)
        self.Button3.configure(activebackground="#ececec")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Add Book''')
        self.Button3.configure(width=77)

        self.Button4 = tk.Button(self.TNotebook2_t1)
        self.Button4.place(relx=0.5, rely=0.884, height=34, width=77)
        self.Button4.configure(activebackground="#ececec")
        self.Button4.configure(activeforeground="#000000")
        self.Button4.configure(background="#d9d9d9")
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(foreground="#000000")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="black")
        self.Button4.configure(pady="0")
        self.Button4.configure(text='''Delete Book''')
        self.Button4.configure(width=77)

    def FillBorrowed(self):
        for i in range(5):
         self.Scrolledtreeview2.insert("","end",text=""+str(i),values=("Trab EL Mass","10/10/2018","20/10/2018"))

# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''

    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)

        #self.configure(yscrollcommand=_autoscroll(vsb),
        #    xscrollcommand=_autoscroll(hsb))
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))

        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')

        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)

        # Copy geometry methods of master  (taken from ScrolledText.py)
        if py3:
            methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        else:
            methods = tk.Pack.__dict__.keys() + tk.Grid.__dict__.keys() \
                  + tk.Place.__dict__.keys()

        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledTreeView(AutoScroll, ttk.Treeview):
    '''A standard ttk Treeview widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        ttk.Treeview.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')



if __name__ == '__main__':
    vp_start_gui()





