#############################################################################
# Generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#  Dec 15, 2018 10:20:06 PM CAT  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} 
    wm focusmodel $top passive
    wm geometry $top 624x467+323+133
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 750
    wm minsize $top 116 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Student" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure TNotebook -background #d9d9d9
    ttk::style configure TNotebook.Tab -background #d9d9d9
    ttk::style configure TNotebook.Tab -foreground #000000
    ttk::style configure TNotebook.Tab -font TkDefaultFont
    ttk::style map TNotebook.Tab -background [list disabled #d9d9d9 selected #d9d9d9]
    ttk::notebook $top.tNo49 \
        -width 624 -height 467 -takefocus {} 
    vTcl:DefineAlias "$top.tNo49" "TNotebook2" vTcl:WidgetProc "Student" 1
    frame $top.tNo49.t0 \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo49.t0" "TNotebook2_t0" vTcl:WidgetProc "Student" 1
    $top.tNo49 add $top.tNo49.t0 \
        -padding 0 -sticky nsew -state normal -text {Borrowed Books} \
        -image {} -compound left -underline -1 
    set site_4_0  $top.tNo49.t0
    ttk::style configure Treeview.Heading -background #d9d9d9
    ttk::style configure Treeview.Heading -font TkDefaultFont
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $site_4_0.scr50 \
        -background {#d9d9d9} -height 377 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 616 
    vTcl:DefineAlias "$site_4_0.scr50" "Scrolledtreeview2" vTcl:WidgetProc "Student" 1
    button $site_4_0.but52 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Borrow New Book} 
    vTcl:DefineAlias "$site_4_0.but52" "Button2" vTcl:WidgetProc "Student" 1
    place $site_4_0.scr50 \
        -in $site_4_0 -x 3 -y 0 -width 616 -relwidth 0 -height 377 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but52 \
        -in $site_4_0 -x 10 -y 390 -width 597 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo49.t1 \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo49.t1" "TNotebook2_t1" vTcl:WidgetProc "Student" 1
    $top.tNo49 add $top.tNo49.t1 \
        -padding 0 -sticky nsew -state normal -text Books -image {} \
        -compound left -underline -1 
    set site_4_1  $top.tNo49.t1
    ttk::style configure Treeview.Heading -background #d9d9d9
    ttk::style configure Treeview.Heading -font TkDefaultFont
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $site_4_1.scr54 \
        -background {#d9d9d9} -height 377 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 624 
    vTcl:DefineAlias "$site_4_1.scr54" "Scrolledtreeview3" vTcl:WidgetProc "Student" 1
    button $site_4_1.but55 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Add Book} 
    vTcl:DefineAlias "$site_4_1.but55" "Button3" vTcl:WidgetProc "Student" 1
    button $site_4_1.but56 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Delete Book} 
    vTcl:DefineAlias "$site_4_1.but56" "Button4" vTcl:WidgetProc "Student" 1
    place $site_4_1.scr54 \
        -in $site_4_1 -x 0 -y 0 -width 624 -relwidth 0 -height 377 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.but55 \
        -in $site_4_1 -x 220 -y 390 -width 77 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.but56 \
        -in $site_4_1 -x 310 -y 390 -width 77 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo49.t2 \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo49.t2" "TNotebook2_t2" vTcl:WidgetProc "Student" 1
    $top.tNo49 add $top.tNo49.t2 \
        -padding 0 -sticky nsew -state normal -text Publishers -image {} \
        -compound none -underline -1 
    set site_4_2  $top.tNo49.t2
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo49 \
        -in $top -x 0 -y 0 -width 624 -relwidth 0 -height 467 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

